config/routes.rb
Rails.application.routes.draw do
  # ログイン用ルーティング(パスワード再設定用ルーティン削除)
  devise_for :users, skip: [:password]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # ログイン後の遷移先ルーティング
  root 'mitumori_forms#new'

  # 確認画面遷移先ルーティング
  post 'mitumori_forms/confirm'

  # 送信完了画面遷移先ルーティング
  post 'mitumori_forms/complete'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mitumori_form.rb
class MitumoriForm
    include ActiveModel::Model
    include ActiveRecord::AttributeAssignment
    
    # 使い捨てカラム
    attr_accessor :genba_name, 
                  :sintiku,
                  :kodate,
                  :floor,
                  :syohin_name,
                  :size, 
                  :door_iti,
                  :grade,
                  :mitumori_kibo_date, 
                  :remark, 
                  :to_mail_address, 
                  :from_mail_address
    
    # 未入力チェック
    # validates :genba_name, 
    #           :size, 
    #           :remark, 
    #           :to_mail_address, 
    #           :from_mail_address, 
    # presence: true
  end 

app/models/mitumori_image.rb
class MitumoriImage < ApplicationRecord
    mount_uploader :image, MitumoriImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,  #:registerable, 新規登録機能削除
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/mitumori_forms_controller.rb
class MitumoriFormsController < ApplicationController
    # ログイン後のみアクセス可能
    before_action :authenticate_user!

    # メールフォーム入力画面遷移時
    def new
        @mitumori_form = MitumoriForm.new
        @mitumori_image = MitumoriImage.new
    end

		 # 確認画面遷移時
    def confirm
        @mitumori_image = MitumoriImage.new(image_confirm_params[:mitumori_image])
        @mitumori_form = MitumoriForm.new(mitumori_form_params)

        # 入力チェック
        if @mitumori_form.valid?
          render :confirm
        else
          render :new
        end
    end

		# メール送信及び添付画像保存
		def complete
      # 添付画像保存      
      @mitumori_form = MitumoriForm.new(mitumori_form_params) 
      @mitumori_image = MitumoriImage.new(image_complete_params[:mitumori_image])
      @mitumori_image.genba_name = @mitumori_form.genba_name
      @mitumori_image.save!
			
      # メール送信
    	MitumoriMailMailer.send_email(@mitumori_form).deliver
      redirect_to root_path
		end

		# 入力したデータをパラメータとしてまとめる
  	private
    # 見積メール送信用パラメータ
  	def mitumori_form_params
    	params.require(:mitumori_form)
            .permit(:genba_name, 
                    :sintiku, 
                    :kodate, 
                    :floor, 
                    :size, 
                    :syohin_name, 
                    :door_iti, 
                    :grade, 
                    :mitumori_kibo_date, 
                    :remark, 
                    :to_mail_address, 
                    :from_mail_address
                  )
  	end

    # 確認画面用添付画像パラメータ
    def image_confirm_params
      params.require(:mitumori_form)
            .permit(mitumori_image:[:image])
    end

    # メール送信及び画像保存時の添付画像用パラメータ
    def image_complete_params
      params.require(:mitumori_form)
            .permit(mitumori_image:[:image_cache])
    end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mitumori_forms_helper.rb
module MitumoriFormsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MitumoriMail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <% if user_signed_in? %>
              <li><%= link_to ' ログアウト', destroy_user_session_path, method: :delete, class: 'glyphicon glyphicon-log-out logout' %></li>
            <% end %>

  <body>
    <%= yield %>
  </body>
</html>

app/views/mitumori_forms/confirm.html.erb
<%= form_for @mitumori_form, :url => mitumori_forms_complete_path do |f| %>
  <table class="table">

  <!-- 現場名 --> 
    <tr>
      <th>現場名</th>
      <td>
        <%= f.hidden_field :genba_name %>
        <%= @mitumori_form.genba_name %>
      </td>
    </tr>

    <!-- 新築/RF -->
    <tr>
      <th>新築/戸建</th>       
      <td>
      <%= f.hidden_field :sintiku %>
      <%= @mitumori_form.sintiku %> 
      </td>
      <td>/</td>
      <!-- 戸建て/マンション -->
      <td>
        <%= f.hidden_field :kodate %>
        <%= @mitumori_form.kodate %> 
        <% if @mitumori_form.kodate == "マンション" %>
          <%= f.hidden_field :floor %>
          (<%= @mitumori_form.floor %>階)
        <% end %>   
      </td>
    </tr>

    <!-- 商品名 -->
    <tr>
      <th>商品名</th>
      <td>
        <%= f.hidden_field :syohin_name %>
        <%= @mitumori_form.syohin_name %>
      </td>
    </tr>

    <!-- サイズ -->
    <tr>
      <th>サイズ</th>
      <td>
        <%= f.hidden_field :size %>
        <%= @mitumori_form.size %>
      </td>
    </tr>

    <!-- ドア位置 -->
    <tr>
      <th>ドア位置</th>
      <td>
        <%= f.hidden_field :door_iti %>
        <%= @mitumori_form.door_iti %>
      </td>
    </tr>

    <!-- グレード -->
    <tr>
      <th>グレード</th>
      <td>
        <%= f.hidden_field :grade %>
        <%= @mitumori_form.grade %>
      </td>
    </tr>

    <!-- 見積希望納期 -->
    <tr>
      <th>見積希望納期</th>
      <td>
      <%= raw sprintf(
            f.date_select(
                :mitumori_kibo_date,
                use_hidden: true,
                selected: Date.new(@mitumori_form.mitumori_kibo_date[1],@mitumori_form.mitumori_kibo_date[2],@mitumori_form.mitumori_kibo_date[3]),
            )
          )
          %>
        <%= @mitumori_form.mitumori_kibo_date[2] %> 月 
        <%= @mitumori_form.mitumori_kibo_date[3] %> 日
      </td>
    </tr>

    <!-- 備考 -->
    <tr>
      <th>備考</th>
      <td>
        <%= f.hidden_field :remark %>
        <%= simple_format(@mitumori_form.remark) %>
      </td>
    </tr>
  </table>

  <!-- 見積添付画像 -->
  <%= image_tag(@mitumori_image.image.url, style: "width: 900px; height: 800px;") %>
    <%= f.fields_for @mitumori_image do |p| %>
    <%= p.hidden_field :image_cache %>
  <% end %>
  
  <%= f.hidden_field :from_mail_address %>
  <%= f.hidden_field :to_mail_address %>
  
  <!-- メール送信ボタン -->
  <%= f.submit '送信' %>
<% end %>

app/views/mitumori_forms/new.html.erb
<%= form_for @mitumori_form, :url => mitumori_forms_confirm_path do |f| %>

	<!--  エラーメッセージ --> 
    <% if @mitumori_form.errors.any? %>
      <div class="alert alert-danger" role="alert">
        <strong>入力内容にエラーがあります</strong>
        <ul>
          <% @mitumori_form.errors.each do |attr, msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
		<!-- メールフォーム --> 
    <table class="table">

      <!-- 現場名入力欄 --> 
      <tr>
        <th>現場名：</th>
        <td><%= f.text_field :genba_name %></td>
      </tr>

      <!-- 新築/RF入力欄 -->
      <tr>    
      <td></td>
        <td>
        <!-- 戸建て/マンション入力欄 -->
          <label><%= f.radio_button :sintiku, "新築" %>新築</label> 
          or
          <label><%= f.radio_button :sintiku, "RF" %>RF</label> 
          /
          <!-- 商品名入力欄 -->
          <label><%= f.radio_button :kodate, "戸建て" %>戸建て</label> 
          or
          <label><%= f.radio_button :kodate, "マンション" %>マンション</label> 
          (<%= f.text_field :floor %>階)
        </td>
        <th>商品名：</th>
        <td><%= f.text_field :syohin_name %></td>
      </tr>

      <!-- サイズ入力欄 -->
      <tr>
        <th>①サイズ：</th>
        <td><%= f.text_field :size %></td>
      </tr>

      <!-- ドア位置入力欄 -->
      <tr class = "door_iti_radio">
        <th>
          ②ドア位置：<br>
          ※画像を選択してください
        </th>
        <td class = "flex-container">
          <%= f.radio_button :door_iti, "RL" %> 
          <label for="mitumori_form_door_iti_rl">
            <%= image_tag 'RL.png' %><br>
            RL
          </label>
          <%= f.radio_button :door_iti, "LR" %> 
          <label for="mitumori_form_door_iti_lr">
            <%= image_tag 'LR.png' %><br>
            LR
          </label>
          <%= f.radio_button :door_iti, "RC" %> 
          <label for="mitumori_form_door_iti_rc">
            <%= image_tag 'RC.png' %><br>
            RC
          </label>
          <%= f.radio_button :door_iti, "LC" %> 
          <label for="mitumori_form_door_iti_lc">
            <%= image_tag 'LC.png' %><br>
            LC
          </label>
      </tr>

      <!-- グレード入力欄 -->
      <tr>
        <th>
          ③グレード：<br>
          例．Zグレードなど
        </th>
        <td>
          <%= f.select :grade, 
            [["Zグレード", "Zグレード"], 
            ["testグレード", "testグレード"]], 
            include_blank: "" %>
        </td>
      </tr>

      <!-- 見積希望納期入力欄 -->
      <tr>
        <th>④見積希望納期：</th>
        <td>
          <%= raw sprintf(
            f.date_select(
                :mitumori_kibo_date,
                use_month_numbers: true,
                discard_year: true,
                date_separator: '%s'), '月 ') + '日'
          %>
        </td>
      </tr>

      <!-- 自由記入欄 -->
      <tr>
        <th>自由記入欄</th>
        <td><%= f.text_area :remark %></td>
      </tr>

      <!-- 見積添付画像選択 -->
      <tr>
        <td>
          <%= f.fields_for @mitumori_image do |i| %>
            <%= i.file_field :image %>
          <% end %>
        </td>
      </tr>

      <!-- 送信元メールアドレス選択 -->
      <tr>
        <td>
          <%= f.select :from_mail_address, 
                [["test01@test", "test01@test"], 
                ["test02@test", "test02@test"]], 
                include_blank: "送信元アドレス" 
          %>
        </td>
      </tr>

      <!-- 送信先メールアドレス選択 -->
      <tr>
        <td>
          <%= f.selct :to_mail_address, 
                [["test01@test", "test01@test"], 
                ["test02@test", "test02@test"]], 
                include_blank: "送信先アドレス" 
          %>
        </td>
      </tr>
    </table>

    <!-- 確認画面遷移ボタン -->
    <%= f.submit '入力完了' %>
  <% end %>